apiVersion: apps/v1
kind: Deployment
metadata:
  name:  optit-lab-service
  namespace: optit-lab
  labels:
    app:  optit-lab-service
spec:
  selector:
    matchLabels:
      app: optit-lab-service
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  optit-lab-service
    spec:
      containers:
      - name:  optit-lab-service
        image:  bharathoptdocker/optit-lab-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort:  8080
          name:  http
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
      restartPolicy: Always