apiVersion: v1
kind: Service
metadata:
  name: optit-lab-service
  namespace: optit-lab
spec:
  selector:
    app: optit-lab-service
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
